RedRoverSchool/BookingProject

- cypress/e2e/testUiAndFunction/startPage/backgroundSection/us_01.16_BackgroundVideo.cy.js
https://trello.com/c/h4WtOmVx/167-at011602-start-page-background-has-video
> AT_01.16.02 | Start Page > Background > Verify the Start Page has video

- cypress/e2e/testUiAndFunction/startPage/loginPopupSection/LoginByEmailTab_UI.cy.js
- cypress/e2e/testUiAndFunction/startPage/loginPopupSection/US_01.05_LoginByEmailTab_UI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/FLIo0AUK/171-at010501-login-by-email-tab-ui-insure-by-email-tab-is-visible
> AT_01.05.01 | Login by email tab UI > Insure By Email tab is visible

- cypress/e2e/testUiAndFunction/leftMenuPanel/menuPanelSection/us_03.01_MenuPanelMainElements.cy.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/CNUGsPY9/138-at030101-left-menu-panel-verify-the-quantity-of-main-elements-icons-in-the-menu
> AT_03.01.01 | Left Menu Panel > Verify the quantity of main elements (icons) in the menu

- cypress/e2e/testUiAndFunction/leftMenuPanel/menuPanelSection/us_03.01_MenuPanelMainElements.cy.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/yHrWmOFY/140-at030102-left-menu-panel-verify-the-names-of-main-elements-in-the-menu
> AT_03.01.02 | Left Menu Panel > Verify the names of main elements in the menu

- cypress/e2e/testUiAndFunction/startPage/loginPopupSection/US_01.05_LoginByEmailTab_UI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/FurBpFt2/206-rf-at010501-spec-and-startpage-pom-login-by-email-tab-ui
> RF | AT_01.05.01  Spec and StartPage POM > Login By Email Tab UI

- cypress/e2e/testUiAndFunction/header/burgerButtonSection/US_02.02_HeaderBurgerMenu.cy.js
- cypress/e2e/testUiAndFunction/leftMenuPanel/menuPanelSection/us_03.01_MenuPanelMainElements.cy.js
- cypress/e2e/testUiAndFunction/leftMenuPanel/menuPanelSection/us_03.03_LeftMenuPanel_BookingsManagementLink.cy.js
- cypress/fixtures/leftMenuPanel/headers.json
- cypress/pageObjects/Header.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/nb5gz7z3/149-at020201-header-burger-menu-functionality-revealing-a-new-menu-panel-on-the-left-side-of-the-page
> AT_02.02.01 | Header > Burger menu UI and functionality > Link names on the left side panel revealed after clicking on the burger menu

- cypress/e2e/testUiAndFunction/startPage/registerAgentAccountPopupSection/us_01.15_RegisterAgentNegative.cy.js
- cypress/fixtures/startPage/alert.json
- cypress/fixtures/startPage/inputField.json
- cypress/fixtures/startPage/registerAgent.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/m5yFkKpt/211-at011501-start-page-register-agent-negative-error-message-is-displayed-when-trying-to-register-without-entering-name
> AT_01.15.01 | Error message is displayed when trying to register without entering name

- cypress/e2e/testUiAndFunction/header/burgerButtonSection/US_02.02_HeaderBurgerMenu.cy.js
https://trello.com/c/OZhNFkha/231-at020202-header-burger-menu-ui-and-functionality-link-names-on-the-left-side-panel-revealed-after-clicking-on-the-burger-menu
> AT_02.02.02 | Header > Burger menu UI and functionality > After second clicking on the burger menu the left side panel is closed

- cypress/e2e/testUiAndFunction/startPage/loginPopupSection/US_01.03_Header_elements.cy.js
- cypress/fixtures/startPage/headers.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/ngleme5s/185-at010302-start-page-login-popup-header-elements-verify-there-is-a-heading-text-element
> AT_01.03.02 | Start Page > Login Popup > Header elements > Verify there is a heading text element

- cypress/e2e/testUiAndFunction/header/leftLogoSection/US_02.01_leftLogoUIandFunc.cy.js
- cypress/pageObjects/Header.js
https://trello.com/c/sICMywwk/209-at020101-header-left-logo-ui-and-functionality-verify-logo-is-visible-clickable-and-redirects-to-default-page
> AT_02.01.01_VerifyLogoIsVisibleUI

- cypress/e2e/testUiAndFunction/header/userDropdownMenuSection/US_02.05UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/3wWbEeaF/223-rf-at020501-verify-the-user-dropdown-menu-displays-selection-of-8-language-icons
> RF | AT_02.05.01 | Verify the User dropdown menu displays selection of 8 language icons'

- cypress/e2e/testUiAndFunction/startPage/registerAgentAccountPopupSection/us_01.15_RegisterAgentNegative.cy.js
- cypress/fixtures/startPage/alert.json
https://trello.com/c/e9Uwgwco/237-rf-specname-testname
> RF_AT_01.15.01

- cypress/fixtures/startPage/inputField.json
https://trello.com/c/51fFqb2H/248-rf-specname-testname
> RF | AT_01.15.01 | Error message is displayed when trying to register without entering name

- cypress/e2e/testUiAndFunction/startPage/registerAgentAccountPopupSection/us_01.15_RegisterAgentNegative.cy.js
- cypress/fixtures/startPage/alert.json
- cypress/pageObjects/StartPage.js
https://github.com/RedRoverSchool/BookingProject/pull/42
> AT_01.15.02 | Error message is displayed when trying to register without company name

- cypress/e2e/testUiAndFunction/startPage/registerAgentAccountPopupSection/us_01.15_RegisterAgentNegative.cy.js
- cypress/fixtures/startPage/alert.json
https://trello.com/c/a1YvKJR8/253-at000000-name
> AT_01.15.03 | Error message is displayed when trying to register without email

- cypress/e2e/testUiAndFunction/leftMenuPanel/contactUsHelpdeskSection/nameUS.cy.js
- cypress/e2e/testUiAndFunction/leftMenuPanel/contactUsHelpdeskSection/us_03.05_LeftMenuPanel_ContactUsLink.cy.js
- cypress/fixtures/leftMenuPanel/menuLinks.json
https://trello.com/c/dYlqyWf0/247-at030501-left-menu-panel-sidebar-has-contact-us-text
> AT_03.05.01 | Left Menu Panel > Sidebar has "Contact us" text

- cypress/e2e/testUiAndFunction/startPage/loginPopupSection/US_01.02_Login_register_section_elements.cy.js
https://trello.com/c/gy4pA8tN/153-at010202-start-page-login-button-visible-clickable-opening-login-popup
> AT_01.02.02 | Start page > Login button: visible / clickable / opening Login popup

- cypress/e2e/testUiAndFunction/startPage/loginRegisterSection/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
- cypress/fixtures/startPage/buttons.json
https://trello.com/c/zfVUydzs/273-at-010203-login-button-has-text-login
> AT 01.02.03 | Login button has text “Login“

- cypress/e2e/testUiAndFunction/header/userDropdownMenuSection/US_02.05UserDropdownMenuUIAndFunc.cy.js
- cypress/pageObjects/Header.js
https://trello.com/c/4Ze54dvJ/215-at020502-user-dropdown-menu-ui-and-functionality-uk-flag-icon-is-displayed-and-clickable
>  AT_02.05.02 | Verify UK flag" icon is displayed and clickable

- cypress/e2e/testUiAndFunction/startPage/multilanguageSection/US_01.01_MultilanguageSectionElements.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/tdBYx9rR/277-at010103-start-page-multilanguage-section-thailand-flag-icon-is-visible
> AT_01.01.03 | Start page > Multilanguage Section > Thailand flag icon is visible

- cypress/e2e/testUiAndFunction/createBookingPage/passengersDetailsSection/US_04.25_functionality-One passenger.cy.js
- cypress/e2e/testUiAndFunction/header/leftLogoSection/US_02.01_leftLogoUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/aRb0sdaj/281-rf-at042501-rewrite-in-pom
> RF | AT_04.25.01 > Rewrite in POMRF

- cypress/e2e/testUiAndFunction/createBookingPage/passengersDetailsSection/US_04.25_functionality-One passenger.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/GjRh6Nrg/282-rf-at042501-create-type-method-in-pom
> RF | AT_04.25.01 > create type method in POM

- cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.11CalendarWeekFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/BlgIFj4Z/229-at041102-calendar-week-functionality-verify-chosen-date-from-calendar-week-current-month-and-year-are-displayed-in-the-departure
> AT_04.11.02 | Verify chosen date, current month and year are displayed in the Departure on section

- cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.09CalendarAvailableDaysWeekUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/tP6wIy9j/286-at040901-verify-calendar-day-selection-wrapper-starts-and-ends-with-same-dates-as-label-calendar-week
> AT_04.09.01 | Verify calendar-day-selection-wrapper starts and ends with same dates as label calendar week

- cypress/e2e/testUiAndFunction/leftMenuPanel/contactUsHelpdeskSection/us_03.05_LeftMenuPanel_ContactUsLink.cy.js
AT_03.05.02|Verify that "Contact us" icon in the left menu panel is visible
> AT_03.05.02 |"Contact us" icon is visible'

- cypress/e2e/testUiAndFunction/bookingsListPage/mainSection/us_05.06_PrintButtonUIandFunc.cy.js
- cypress/pageObjects/BookingsListPage.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/XgWiN0up/300-at050601-booking-list-page-verify-that-the-print-button-is-displayed
> AT_05.06.01 | Booking list page > Verify that the "Print" button is displayed

- cypress/e2e/testUiAndFunction/startPage/multilanguageSection/US_01.01_MultilanguageSectionElements.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/MR7QxpD5/142-at010101-start-page-verify-russia-flag-icon-is-visible
> AT_01.01.01 | Start page > Verify Russia flag icon is visible

- cypress/e2e/testUiAndFunction/bookingsListPage/mainSection/us_05.06_PrintButtonUIandFunc.cy.js
- cypress/fixtures/bookingsListPage/buttons.json
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/94n1zUBS/290-at050602-booking-list-page-verify-that-the-print-button-has-the-text-print-and-an-icon
> AT_05.06.02 | Booking list page > Verify that the "Print" button has the text "Print" and an icon

- cypress/e2e/testUiAndFunction/header/envelopeIconSection/us_02.03_Header_EnvelopeIconUIandFunc.cy.js
- cypress/pageObjects/Header.js
TC - https://trello.com/c/tjjzwfaO/173-tc020301-header-envelope-icon-ui-and-functionality-verify-envelope-icon-is-visible
AT - https://trello.com/c/W3v3qOxd/174-at020301-header-envelope-icon-ui-and-functionality-verify-envelope-icon-is-visible
> AT_02.03.01_Verify Envelope icon is visible.

- cypress/e2e/testUiAndFunction/leftMenuPanel/contactUsHelpdeskSection/us_03.05_LeftMenuPanel_ContactUsLink.cy.js
- cypress/fixtures/helpdeskPage/headers.json
- cypress/pageObjects/HelpdeskPage.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/6rY6vN83/302-at030503-verify-that-clicking-contact-usopening-helpdesk-page-with-a-header-helpdesk
> AT_03.05.03 | Verify that clicking "Contact us"opening Helpdesk page with a header "Helpdesk

- cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/XsfAuKCa/245-at040803-create-booking-page-departure-date-calendar-selection-block-ui-and-functionalityverify-that-lable-is-present-for-week-v
> AT_04.08.03 | Calendar-selection block UI and functionality week view

- cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.09_CalendarAvailableDaysWeekUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.11_CalendarWeekFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/3wWbEeaF/223-rf-change-2-elements-name-in-createbooking-pom
> RF | Change 2 elements name in CreateBookingPage.js

- cypress/e2e/testUiAndFunction/createBookingPage/seatSelectionSection/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/YP0b20Gu/189-at042802-seat-selection-dropdown-is-visible-and-displays-the-number-of-passengers-selected-in-the-passengers-details-dropdown
> AT_04.28.02 | "Seat selection dropdown" is visible and displays the number of passengers, selected in the "Passengers details dropdown"

- cypress/e2e/testUiAndFunction/header/userDropdownMenuSection/US_02.05_UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/YIVJnkQY/324-rf-at020502-verify-uk-flag-icon-is-displayed
> RF | AT_02.05.02 > Verify UK flag" icon is displayed

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.09_CalendarAvailableDaysWeekUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
[AT_04.09.02 | Verify that the active field has background color #00a65a and text color #FFFFFF](https://trello.com/c/mshG7s7p/332-at040902-verify-that-the-active-field-has-background-color-00a65a-and-text-color-ffffff)
> AT_04.09.02 | Verify that the active field has background color #00a65a and text color #FFFFFF

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/3zMSgPo6/336-at042901-the-amount-of-passengers-in-the-seat-selection-dropdown-is-equal-the-number-of-available-tickets-in-the-selected-trip
> AT_04.29.01 | The amount of passengers in the "Seat selection dropdown" is equal the number of available tickets in the selected trip

- cypress/e2e/testUiAndFunction/startPage/US_01.12_FooterUIandFunc.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/aleMsnIg/305-at011202-start-page-register-agent-account-popup-footer-ui-and-functionality-insure-footer-elements-are-visible
> AT_01.12.02 | Insure Footer elements are visible

- cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
- cypress/fixtures/startPage.json
- package-lock.json
- package.json
https://trello.com/c/cswuHCnK/343-rf-us0115registeragentnegative-add-faker
> RF US_01.15 and install faker

- cypress/e2e/testUiAndFunction/startPage/US_01.01_MultilanguageSectionElements.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/quO2VtYM/246-at010102-start-page-verify-russia-flag-icon-clickable-changing-language-to-russian
> "AT_01.01.02 | Verify Russia flag icon: clickable / changing language to Russian"

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/6aZYTcpq/314-at041303-create-booking-page-departure-date-verify-that-the-label-of-the-month-dropdown-displays-the-month-selected-from-the-mon
> AT_04.13.03 | Verify that the label of the Month dropdown displays the month selected from the Month dropdown menu

- cypress/pageObjects/StartPage.js
https://trello.com/c/J9cO5Z5I/352-rf-startpagejs-delete-duplicate-element
> RF | StartPage.js > Delete duplicate element

- cypress/e2e/testUiAndFunction/header/US_02.02_HeaderBurgerMenu.cy.js
- cypress/fixtures/leftMenuPanel.json
https://trello.com/c/ul5RcUbk/353-rf-leftmenupaneljson-moved-data
> RF | leftMenuPanel.json > Moving data

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
https://trello.com/c/7mdSpWZl/243-at040801-create-booking-page-departure-date-calendar-selection-block-ui-and-functionalityverify-that-lable-is-present-for-month
> AT_04.08.01 | Calendar-selection block UI and functionality

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.09_CalendarAvailableDaysWeekUI.cy.js
- cypress/fixtures/createBookingPage.json
[RF|AT_04.09.02 | Verify that the active field has background color #00a65a and text color #FFFFFF](https://trello.com/c/hMOAA539/355-rf040902-verify-that-the-active-field-has-background-color-00a65a-and-text-color-ffffff)
> RF |AT_04.09.02 |  Verify that the active field has background color #00a65a and text color #FFFFFF

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
https://trello.com/c/07Vc9nAS/294-at041202-verify-any-available-chosen-date-month-and-year-from-month-dropdown-menu-match-label-departure-on-date
> AT_04.12.02 | Verify any available chosen date, month and year from month dropdown menu match label departure on date

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.06_DepartureDropdown.cy.js
https://trello.com/c/wg5sMOad/356-rf-createbookingpage-departure-dropdown-at040602
> RF | CreateBookingPage >Departure dropdown > AT_04.06.02

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
[AT_04.11.03 | Create booking page > Deparure date > Calendar week functionality >Verify that if the date has expired, then the field with it is not clickable](https://trello.com/c/QavnQNED/257-at041103-create-booking-page-deparure-date-calendar-week-functionality-verify-that-if-the-date-has-expired-then-the-field-with-i)
[TC_04.11.03 | Create booking page > Deparure date > Calendar week functionality >Verify that if the date has expired, then the field with it is not clickable](https://trello.com/c/SaX1QQCi/250-tc041103-create-booking-page-deparure-date-calendar-week-functionality-verify-that-if-the-date-has-expired-then-the-field-with-i)
> AT_04.11.03 | Verify that if the date has expired, then the field with it is not clickable

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.07_ArrivalDropdown.cy.js
- cypress/pageObjects/CreateBookingPage.js
TC - https://trello.com/c/gnsRNo2L/344-tc040701-create-booking-page-arrival-dropdown-ui-and-functionality-verify-the-arrival-station-dropdown-menu-is-clickable-and-ope
AT - https://trello.com/c/g2zfMR5Y/345-at040701-create-booking-page-arrival-dropdown-ui-and-functionality-verify-the-arrival-station-dropdown-menu-is-clickable-and-ope
> AT_04.07.01 | Verify the Arrival station Dropdown Menu is clickable and opens up the dropdown menu.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/DcqhLGE9/337-at042902-the-list-of-passengers-starts-with-1-passenger-and-each-subsequent-element-increases-by-one
> AT_04.29.02 | The list of passengers starts with "1 passenger" and each subsequent element increases by one

- cypress/e2e/testUiAndFunction/bookingsListPage/us_05.06_PrintButtonUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/header/US_02.01_leftLogoUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/header/US_02.02_HeaderBurgerMenu.cy.js
- cypress/e2e/testUiAndFunction/leftMenuPanel/US_03.05_ContactUsLink.cy.js
- cypress/e2e/testUiAndFunction/leftMenuPanel/us_03.01_MenuPanelMainElements.cy.js
- cypress/e2e/testUiAndFunction/leftMenuPanel/us_03.03_BookingsManagementLink.cy.js
- cypress/pageObjects/Header.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/7t8JLJ8U/367-rf-us0201leftlogouiandfunc-at020102
> RF | US_02.01_leftLogoUIandFunc

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/SXoMGxep/298-at041201-create-booking-page-verify-any-date-earlier-than-the-current-date-is-not-available
> AT_04.12.01 | Verify any date earlier than the current date is not available.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
https://trello.com/c/7mdSpWZl/243-at040801-create-booking-page-departure-date-calendar-selection-block-ui-and-functionalityverify-that-lable-is-present-for-month
> AT_04.08.01 |  Calendar-selection block UI and functionality

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/S2YgmpUc/339-at010801-start-page-verify-phone-number-label-is-visible
> AT_01.08.01 | Verify 'Phone number' label is visible

- cypress/e2e/testUiAndFunction/startPage/US_01.02_Login_register_section_elements.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.03_Header_elements.cy.js
- cypress/pageObjects/Header.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/8Uwdzce0/387-rf-us0103headerelements-at010301
> RF | US_01.03_Header_elements > AT_01.03.01

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/OLxF7sd6/388-rf-us0413-code-from-beforeeach-moved-to-before
> RF | US_04.13 | beforeEach -> before and clean some code that was never used

- cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
https://trello.com/c/jxvQliut/382-at011508-error-message-is-displayed-when-trying-to-register-with-invalid-company-name-1-letter-and-1-number-without-space-exampl
> AT_01.15.08 | Error message is displayed when trying to register with invalid company name (1 letter and 1 number without space , example: "A1")'

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
https://trello.com/c/0bNhohBW/401-rf-changed-date-properties-in-at041302-add-at041102
> RF | Change Date object properties in AT_04.13.02 add AT_04.11.02

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/0EhzgXon/358-at042903-when-selecting-the-required-amount-of-passengers-the-corresponding-number-of-seats-in-the-seats-table-will-be-9dd09d-co
> AT_04.29.03 | When selecting the required amount of passengers the corresponding number of seats in the "Seats table" will be rgb(157, 208, 157) color

- cypress/e2e/testUiAndFunction/header/US_02.02_HeaderBurgerMenu.cy.js
https://trello.com/c/MQBCU7Uv/409-rf-at020201-at020202
> RF | AT_02.02.01, AT_02.02.02 tests union

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/ieOj0RmJ/390-at020506-thai-flag-icon-is-clickable
> Verify TH flag icon is clickable

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
https://trello.com/c/IdaSJgsk/412-at041305-create-booking-page-departure-date-verify-that-the-calendar-label-between-arrows-displays-the-month-selected-from-the-d
> AT_04.13.05 | Calendar label (between arrows) displays the month selected from the dropdown menu

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.09_CalendarAvailableDaysWeekUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/GEuHILPp/362-at040903-create-booking-page-departure-date-calendar-available-days-week-ui-in-all-inactive-fields-the-number-has-the-color-3333
> AT_04.09.03 | Create booking page > Departure date > Calendar available days week UI > In all inactive fields the number has the color #333333

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/gHUaONis/434-at010803-start-page-login-popup-login-by-phone-number-verify-phone-number-input-field-has-placeholder-1234567
> AT_01.08.03 | Verify "Phone number" input field has placeholder `1234567`

- cypress/e2e/testUiAndFunction/startPage/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
Verify  that the Register account link is visible and when clicking this link, an agent pop-up is displayed
> AT_01.02.05 | Verify link 'Register account' is visible and clickable

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/37TL0IYE/350-tc010802-start-page-verify-country-code-label-has-placeholder-66
> AT_01.08.02 | Verify Country code label has placeholder - '66'

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
https://trello.com/c/aKNLroFp/178-at040804-create-booking-page-departure-date-calendar-selection-block-ui-and-functionalityverify-that-click-forward-arrow-work-an
> AT_04.08.04 | Verify that Click forward arrow works and switches month in correct order

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.04_CreditBalanceButtonUIandFunc.cy.js
https://trello.com/c/Il2JiXnO/373-at040401-create-booking-page-verify-that-week-month-format-lable-week-2-oct-8-oct-month-oct-2023
> AT_04.04.01 | Create booking page > Verify that week/month format lable (week => "2 Oct - 8 Oct", month => "Oct 2023")

- cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
https://trello.com/c/Aerw5xpg/460-at011510-start-page-register-agent-negative-error-message-is-displayed-when-trying-to-register-with-invalid-phone-number-letters
> AT_01.15.10 | Verify  error message is displayed when trying to register with invalid phone number

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/RbPac7Fs/443-at041306-name
> AT_04.13.06 | Month dropdown menu > Month that is shown in the "Departure on" section displays the month selected from the dropdown menu.

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/aCGq43we/466-at010804-start-page-login-popup-verify-country-code-label-has-color-aaa
> AT_01.08.04 | Start Page > Login Popup > Verify `Country code` label has color - #aaa

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.10_ExcelButtonUIandFunc.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/Y1Z82QMj/465-at051001-booking-management-bookings-list-page-main-section-verify-that-excel-button-displayed
> AT_05.10.01 | Verify that Excel button displayed

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
https://trello.com/c/9E3LXUI8/455-at040805-verify-previous-arrow-button-switches-weeks-in-descending-order-from-3-weeks-ahead
> AT_04.08.05 | Verify previous arrow button switches weeks in descending order from 3 weeks ahead

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.10_ExcelButtonUIandFunc.cy.js
- cypress/fixtures/bookingsListPage.json
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/tmhCpqwG/475-at051002-verify-if-the-excel-button-has-text-excel-and-icon
> AT_05.10.02 | Verify if the "Excel" button has text "Excel" and icon

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/YMPJQnBU/477-at042803-verify-number-of-default-selected-seats-equals-number-of-selected-passengers-from-passenger-details-dropdown-menu
> AT_04.28.03 | Verify number of default selected seats equals number of selected passengers from passenger details dropdown menu

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/7Svc9oUX/363-at042302-verify-main-passenger-label-is-visible
> AT_04.23.02 | Verify ‘Main passenger’ label is visible.

- cypress/e2e/testUiAndFunction/leftMenuPanel/US_03.04_AccountManagementLink.cy.js
- cypress/fixtures/leftMenuPanel.json
https://trello.com/c/DR04pVv8/472-at030402-left-menu-panel-account-management-link-at030402-verify-the-sidebar-has-text-account-management
> AT_03.04.02 Verify the Sidebar has text "Account management"

- cypress/e2e/testUiAndFunction/startPage/US_01.11_Header elements.cy.js
https://trello.com/c/4N7Rbhmu/457-at011101-name
> AT_01.11.01 | Verify that title `Register agent account` are visible in the header

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/DPRtqnNi/485-at020510-verify-de-flag-icon-is-displayed
> AT_02.05.10 | Verify flag icon is displayed

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05_01_TopSection_SeachFormUI.cy.js
- cypress/fixtures/bookingsListPage.json
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/8U0XBW1B/385-tc050101-booking-list-page-top-section-search-input-field-default-ui
> TC_05.01.01 | Booking list page >Top section > Search input field default UI

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
https://trello.com/c/bQqrz4le/393-at011509-start-page-register-agent-negative-error-message-is-displayed-when-user-attempts-to-register-with-special-characters-in
> AT_01.15.09 | Verify error message is displayed when user attempts to register with special characters in `Company name` field'

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/gdxVThvi/492-at010509-name
Skipped tests AT_04.12.01 and AT_04.13.02 Requested by Olga B
https://trello.com/c/JFHkkQng/494-err-createbookingpage-at041201-and-at041302
> AT_01.05.09 | Verify SIGN IN button has text 'SIGN IN'

- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
https://trello.com/c/4k8Skio6/499-at010510-verify-sign-in-button-is-visible-and-clickable
> AT_01.05.10 | Verify SIGN IN button is visible and clickable

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js
- cypress/fixtures/createBookingPage.json
[TC_04.11.04|Verify that when you hover the cursor over any valid date, the cursor sign appears](https://trello.com/c/YPWTZPGE/251-tc041104-create-booking-page-deparure-date-calendar-week-functionality-verify-that-when-you-hover-the-cursor-over-any-valid-date)
[AT_04.11.04|Verify that when you hover the cursor over any valid date, the cursor sign appears](https://trello.com/c/xYqD5UDO/258-at041104-create-booking-page-deparure-date-calendar-week-functionality-verify-that-when-you-hover-the-cursor-over-any-valid-date)
> AT_04.11.04|Verify that when you hover the cursor over any valid date, the cursor sign appears

- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
https://trello.com/c/MT2uurh5/501-at010506-verify-sign-in-button-has-color-6ccd66
> AT_01.05.06 | Verify SIGN IN button has color - #6CCD66

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/support/utilities/createArrayOfMonths.js
https://trello.com/c/h1r3g6De/504-rf-at041302-at041304
> RF | AT_04.13.02 , AT_04.13.04

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/RbPac7Fs/443-at041306-create-booking-page-departure-date-month-dropdown-ui-and-functionality-month-that-is-shown-in-the-departure-on-section
> RF | AT_04.13.06 add method getRandomIndexOfMonth()

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/PC4xe2fD/490-at010805-start-page-login-popup-verify-country-code-label-has-font-size-10px
> AT_01.08.05 | Start Page > Login Popup > Verify Country code label has font-size - 10px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/1TFQFZMI/519-rf-at041305-testname
> RF | AT_04.13.05 start using getRendomIndexOfMonth() method

- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.07_LoginByEmailTab_negative.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.09_LoginByPhoneNumberTabFunc.cy.js
- cypress/e2e/testUiAndFunction/startPage/us_01.06_LoginByEmailTub.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/EwZt6knT/517-at010901-verify-after-clicking-sign-in-button-be-redirected-to-create-booking-page
> AT_01.09.01 | Verify after clicking Sign in button be redirected to Create booking page

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/rGC4tMAF/498-at010806-start-page-login-popup-verify-country-code-label-has-text-country-code
> AT_01.08.06 | Start Page > Login Popup > Verify `Country code` label has text 'Country code'

- cypress/e2e/testUiAndFunction/startPage/US_01.11_Header elements.cy.js
https://trello.com/c/1c5ED2NP/518-at011102-name
> AT_01.11.02 | Verify that the title `Register agent account` has rgb(102, 102, 102) color, and 30px font-size‌

- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/C6lhRM8P/523-rf-createbookingpage
> RF CreateBookingPage > add description of sections

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
- cypress/pageObjects/Header.js
https://trello.com/c/pHgBORML/470-at020507-verify-user-dropdown-menu-has-sign-out-button
> AT_02.05.07| Verify "User dropdown menu" has "Sign out" button

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/wAv0iVuM/532-at042303-verify-passenger-name-input-field-has-a-passenger-name-text-placeholder
> AT_04.23.03 | Verify passenger name input field has a “Passenger name” text placeholder.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/uoTnMy95/531-at042808-create-booking-page-seat-selection-ui-and-functionalit-the-total-number-of-seats-in-the-seat-selection-section-is-equal
> AT_04.28.08 | The total number of seats in the "Seat selection" section is equal the total number of seats in the selected trip

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/htnNvzey/544-at020503-clicking-sign-out-button-gets-user-signed-out
> AT_02.05.03 | Clicking "Sign out" button gets user signed out

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
https://trello.com/c/ezoQImB3/546-rf-us0429-remove-cywait
> RF | US_04.29 > remove cy.wait()

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/yKZjNJTx/524-at043001-displayed-seats-match-default-seat-selection-from-seat-selection-section
> AT_04.30.01 | Displayed seats match default seat selection from seat selection section

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/PcMxh07t/526-at041501-create-booking-page-month-button-elements-view-selected-month-button-is-visible-has-the-attribute-selected-and-its-back
> AT_04.15.01 | Create booking page > selected Month button is visibility

- cypress/e2e/testActions/nameUS.cy.js
- cypress/e2e/testActions/us_AC.05_CreateReservation.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
- cypress/pageObjects/BookingPopup.js
- cypress/pageObjects/CreateBookingPage.js
- cypress/support/utilities/waitFor.js
https://trello.com/c/MPdQSelD/418-atac0502-create-reservation-for-1-passenger-child
> AT_AC.05.02| Create reservation for 1 passenger - Child

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.09_CalendarAvailableDaysWeekUI.cy.js
- cypress/fixtures/createBookingPage.json
TC - https://trello.com/c/4GwgfiZv/548-tc040905-calendar-available-days-week-uiverify-that-the-seven-fields-are-displayed-for-the-week
AT - https://trello.com/c/hiJ5q63m/549-at040905-calendar-available-days-week-uiverify-that-the-seven-fields-are-displayed-for-the-week
> AT_04.09.05 | Seven fields are displayed for the week.

- cypress/e2e/testUiAndFunction/leftMenuPanel/us_03.01_MenuPanelMainElements.cy.js
https://trello.com/c/uYOf8M8j/556-rf-specname-testname
> RF | US_03.01_MenuPanelMainElements.cy.js

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/oJkOR8CL/559-at043003-verify-total-number-of-rows-equals-number-of-chosen-passengers-from-passenger-dropdown-menu
> AT_04.30.03 | Verify total number of rows equals number of chosen passengers from passenger dropdown menu

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
- cypress/fixtures/header.json
https://trello.com/c/L47gtoHA/564-rf-specname-testname
> RF | AT_02.05.01

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/R43QaFOy/566-at000000-section-sections-unititem
> AT_04.23.05 | Verify phone number input field has a “Phone number” text placeholder.

- cypress/e2e/testActions/US_AC.01_RegisterNewAgent.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
Register a new agent action - from the beginning to the end
> AT_AC.01.02 Register a new agent action

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.04_CreditBalanceButtonUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/dkbX1B24/570-rf-us0428-at042802-add-getrandompassengersammount
> RF | US_04.28 > AT_04.28.02 > add getRandomPassengersAmmount

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/BZrqWbsM/577-at010807-start-page-login-by-phone-number-tab-ui-verify-the-agent-is-able-to-see-phone-number-input-field
> AT_01.08.07 | Start Page > Login by phone number tab UI > Verify the agent is able to see 'Phone number' input field

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/7mJyCEgm/505-at042905-verify-number-of-passengers-selected-in-the-seat-selection-dropdown-became-equal-to-the-number-of-passengers-in-the-sum
> 04.29.05 | Verify number of passengers selected in the "Seat selection dropdown" became equal to the number of passengers in the "Summary" section

- cypress/e2e/testUiAndFunction/startPage/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/zgpKv1z0/573-at010207-start-page-verify-that-the-login-register-section-has-a-white-ffffffe0-background-color
> AT_01.02.07 | Verify that the Login-register section has a white #ffffffe0 background color

- cypress/e2e/testUiAndFunction/header/US_02.04_UserDropdownMenuButtonUIandFunc.cy.js
- cypress/pageObjects/Header.js
TC - https://trello.com/c/0p2jKgYN/580-tc020401-header-user-dropdown-menu-button-ui-and-functionalityuser-dropdown-menu-button-contains-an-operator-image
AT - https://trello.com/c/1mT4Xyz3/581-at020401-header-user-dropdown-menu-button-ui-and-functionalityuser-dropdown-menu-button-contains-an-operator-image
> AT_02.04.01 "User dropdown menu" button contains an "Operator Image"

- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/gQ9gF7TB/536-tc010508-verify-sign-in-button-has-border-color-6ccd66
> AT_01.05.08 | Verify SIGN IN button has border-color - #6CCD66

- cypress/pageObjects/StartPage.js
https://trello.com/c/2JDylTfs/589-rf-startpage-pom-changing-of-phonenumberlabel-selector
> RF | StartPage POM > Changing of PhoneNumberLabel selector

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
https://trello.com/c/y6LnCX1M/591-rf-at042903-add-getrandomamountofpassseatselectiondrpdwn-method
> RF | AT_04.29.03 > add getRandomAmountOfPassSeatSelectionDrpDwn() method

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/sFosrYbm/579-at010808-start-page-login-by-phone-number-tab-ui-verify-the-agent-is-able-to-see-country-code-input-field
> AT_01.08.08| Start Page > Login by phone number tab UI > Verify the agent is able to see 'Country code' input field

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/Ek5J7QDF/541-at043002-summary-ui-total-price-is-correct
> AT_04.30.02| Total price is correct

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/MpcR6I1K/584-at010809-start-page-login-by-phone-number-tab-ui-verify-phone-number-label-has-text-phone-number
> AT_01.08.09 | Verify Phone number label has text 'Phone number'

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js
[AT_04.11.06|Verify that when you click on the first and last date, its value matches the date in the string in the *Calendar-selection block*](https://trello.com/c/REX4BTQT/422-at041106-create-booking-page-deparure-date-calendar-week-functionality-verify-that-when-you-click-any-valid-date-the-string-in-t)
[TC_04.11.06| Verify that when you click on the first or last date, its value matches the date in the string in the *Calendar-selection block*](https://trello.com/c/e1QmkJbE/421-tc041106-create-booking-page-deparure-date-calendar-week-functionality-verify-that-when-you-click-on-the-first-or-last-date-its)
> AT_04.11.06|Verify that when you click on the first and last date, its value matches the date in the string in the *Calendar-selection block*

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/R29VJG6o/604-at042805-the-title-of-seats-table-is-visible-and-matches-to-the-class-of-the-selected-trip-vip-bus
> AT_04.28.05 | The title of "Seats table" is visible and matches to the class of the selected trip "VIP bus"

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/l1y4Yywr/598-at010810-start-page-login-by-phone-number-tab-ui-verify-phone-number-label-has-color-aaa
> AT_01.08.10| Start Page > Login by phone number tab UI > Verify 'Phone number' label has color - #aaa

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.06_DepartureDropdown.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/Z4gNKaxO/609-at040603-create-booking-page-departure-dropdown-ui-and-functionality-verify-that-the-background-of-the-selected-item-in-the-drop
> AT_04.06.03 | Verify that the background of the selected item in the Dropdown Menu has gray color (#DDDDDD)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/4Gjmjb5E/601-at040806-create-booking-page-departure-date-calendar-selection-block-ui-and-functionalityverify-that-click-back-arrow-works-and
> AT_04.08.06 | <Create booking page > Verify that Click back arrow works and switches month in correct order>

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/l2ipal3b/599-rf-specname-testname
> RF | US_02.05, US_04.12 | add before , context to US_02.05

- cypress/e2e/testUiAndFunction/startPage/us_01.16_BackgroundVideo.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/IUFsN4aJ/222-rf-at011602-rewrite-in-pom
> RF | US_01.16_ChangeBeforeEachToBefore

- cypress/e2e/testUiAndFunction/header/US_02.04_UserDropdownMenuButtonUIandFunc.cy.js
- cypress/pageObjects/Header.js
TC - https://trello.com/c/QLQa9GtH/585-tc020402-header-user-dropdown-menu-button-ui-and-functionality-user-dropdown-menu-button-is-clickable-and-opens-up-the-dropdown
AT - https://trello.com/c/LipjfLfY/586-at020402-header-user-dropdown-menu-button-ui-and-functionality-user-dropdown-menu-button-is-clickable-and-opens-up-the-dropdown
> AT_02.04.02 |"User dropdown menu" button is clickable and opens up the dropdown menu

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.07_ArrivalDropdown.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.25_functionality-One passenger.cy.js
https://trello.com/c/4VFItFU6/612-rf-us0425-us0407
> RF | US_04.25, US_04.07

- cypress/e2e/testUiAndFunction/startPage/US_01.01_MultilanguageSectionElements.cy.js
https://trello.com/c/pd2oFTAh/618-rf-us0101
> RF | US_01.01

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
https://trello.com/c/Wm2ZdEVg/619-rf-us0424
> RF | US_04.24

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/zskTwoT9/582-tc050302-date-filter-ui-verify-that-the-calendar-dropdown-has-defaulted-to-the-current-date-in-format-dd-mmm-yyyy
> AT_05.03.02| Verify that the "calendar" has default format DD MMM, YYYY - DD MMM, YYYY

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/pdDiD6Zn/587-at042304-verify-selected-dial-code-is-66-by-default
> AT_04.23.04 | Verify selected dial code is “+66” by default

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/5e0hxPWH/625-rf-at042811
> PF | AT_04.28.11

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/support/utilities/getStartAndEndOfTheWeek.js
https://trello.com/c/lUQ47U19/629-at040802-verify-that-calendar-lable-shows-week-range-in-correct-format-from-monday-to-sunday
> AT_04.08.02 | Verify that Calendar Label shows week range in correct format from Monday to Sunday

- cypress/e2e/testActions/us_AC.05_CreateReservation.cy.js
Create reservation for 1 passenger -Adult
> AT_AC.05.01 Create reservation for 1 passenger -Adult

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/voLGx6PU/631-at042306-verify-dial-code-selection-arrow-is-present-and-visible
> AT_04.23.06 | Verify dial code selection arrow is present and visible.

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/fixtures/bookingsListPage.json
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/9yQkzllc/626-tc050305-date-filter-ui-verify-that-the-filter-date-range-dropdown-has-values
> AT_05.03.05 | Verify that the filter date range dropdown has values

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/ow6ItLfY/637-rf-bookinglistpage
> RF | BookingListPage

- cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
https://trello.com/c/AZUT0IDt/642-rf-us0115registeragentnegative
> RF | US_01.15_RegisterAgentNegative

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/MZnATXWT/649-at010811-section-sections-unititem
> AT_01.08.11 | Verify Phone number label has text 'Phone number'

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/B2Ne9UcD/654-at011104-verify-that-after-clicking-on-the-x-button-in-the-top-right-corner-register-agent-account-popup-window-is-closed-and-th
> AT_01.08.12 | Verify the agent is able to see Country code input field

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/fixtures/bookingsListPage.json
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/tFHcPOpw/644-at050304-verify-that-the-filter-datetype-dropdown-has-defaulted-text-by-purchase-date
> Verify that the  AT_05.03.04 DateType dropdown is visible and have 2 options

- cypress/e2e/testUiAndFunction/startPage/US_01.11_Header elements.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/B2Ne9UcD/654-at011104-verify-that-after-clicking-on-the-x-button-in-the-top-right-corner-register-agent-account-popup-window-is-closed-and-th
> AT_01.11.04 | Verify the functionality of close button

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/ZG1T1fpx/658-rf-us042811-add-context
> RF | AT_04.28.11 > add context to test 

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/pageObjects/BookingPopup.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/bz9BJxTQ/482-at042807-create-booking-page-seat-selection-ui-and-functionality-the-number-of-available-seats-in-the-seat-selection-section-is
> AT_04.28.07 | The number of available seats in the "Seat selection" section is equal the number of available seats in the selected trip

- cypress/e2e/testUiAndFunction/startPage/US_01.11_Header elements.cy.js
https://trello.com/c/QvnnnnRs/661-rf-us0111changingbeforeeachtobefore
> RF | US_01.11_ChangingBeforeEachToBefore

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/cUq5JRNM/638-at042809-when-unselecting-the-seat-in-the-seats-table-in-the-summary-section-the-red-color-text-select-seat-appears
> AT_04.28.09 | When unselecting the seat in the "Seats table" in the "Summary" section the red color text "Select seat" appears

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/SS8NghrK/663-tc052301-booking-management-reserve-tickets-booking-details-popup-verify-departure-time-is-in-24-hour-notation-hhmm
> AT_05.23.01 |  Verify departure time is in 24-hour notation HH:MM

- cypress/e2e/testUiAndFunction/leftMenuPanel/US_03.04_AccountManagementLink.cy.js
- cypress/fixtures/accountManagementPage.json
- cypress/pageObjects/AccountManagementPage.js
- cypress/pageObjects/LeftMenuPanel.js
https://trello.com/c/zxoPlyvo/545-at030403-clicking-account-management-opening-the-page-with-heading-account-management
> AT_03.04.03 Clicking "Account management" opening the page with heading "Account management"

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/DxrQuROA/667-rf050305-verify-that-the-filter-date-range-dropdown-has-values
> RF_05.03.05 | Verify that the filter date range dropdown has values

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.06_DepartureDropdown.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/8w90ORbE/669-at040604-create-booking-page-departure-dropdown-ui-and-functionality-verify-that-the-background-of-the-newly-selected-item-chang
> AT_04.06.04 | Verify that the background of the newly selected item changes color to green(#00A65A) when the item is selected

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/MStyRrgp/635-at042202-verify-trip-card-are-sorted-in-descending-order-if-latest-button-is-clicked
> AT_04.22.02 | Verify trip cards are sorted in descending order if "latest" button is clicked

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/vExbBrPA/672-at052303-booking-management-reserve-tickets-booking-details-popup-verify-arrival-time-is-in-24-hour-notation-hhmm
> AT_05.23.03 | Booking management > Reserve tickets / Booking Details popup> Verify arrival time is in 24-hour notation HH:MM

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/OXCuvCjK/674-tc041507-create-booking-page-month-button-elements-view-selected-day-by-default-is-according-to-requirements-current-date-by-gmt
> AT_04.15.07 | Selected day by default is according to requirements (current date by (GMT+7) + 2 days)

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/ZWvkNUoT/673-at010814-login-by-email-tab-ui-insure-popup-background-color-is-fff
> AT_01.08.14 | Insure Popup background color is #fff

- cypress/e2e/testActions/us_AC.05_CreateReservation.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/HDVU7eUn/676-rf-create-booking-page-change-locators-names
> RF | Create Booking Page > Change locators names

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/oVNLYef6/679-rf-at041504-create-booking-page-month-button-elements-view-departure-date-section-has-the-label-departure-date
> RF_AT_04.15.04

- cypress/e2e/testUiAndFunction/startPage/us_01.17_HeaderElements.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/9Wq6EkqR/678-at011702-restore-password-popupfrom-login-popup-verify-an-agent-user-is-able-to-see-the-heading-restore-password
> AT_01.17.02 | Verify an Agent/User is able to see the heading `Restore password`

- cypress/e2e/testUiAndFunction/startPage/US_01.10_LoginByPhoneNegative.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/MbMNvL0A/683-at011001-verify-that-registering-is-not-possible-with-empty-country-code-input
> AT_01.10.01 | Verify that registering is not possible with empty 'Country code' input

- cypress/e2e/testUiAndFunction/startPage/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/9Q3EybnR/682-at010209-background-of-login-section-is-white-ffffff
> AT_01.02.09 | Background of login button is white rgb(255, 255, 255)

- cypress/e2e/testUiAndFunction/startPage/US_01.04_LoginPopupFooterUIandFn.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/zbiyNOUx/689-at010403-verify-the-functionality-of-the-register-link
> AT_01.04.03 | Verify the functionality of the Register link

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
https://trello.com/c/lSrFgQlS/686-tc042307-verify-email-input-field-has-an-email-text-placeholder
> TC_04.23.07 | Verify email input field has an “Email” text placeholder.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/NeIWlDch/690-rf-at040505-create-a-method-of-getting-current-month-and-year
> RF | AT_04.15.05

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/YZdYN6aR/694-at010813-start-page-login-popup-login-by-phone-number-verify-request-code-button-is-visible
> AT_01.08.13 | Verify REQUEST CODE button is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/EKamGR4k/407-at043102-verify-that-total-has-no-value-by-default
> AT_04.31.02 |Verify that "Total" has no value by default.

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
- cypress/pageObjects/Header.js
https://trello.com/c/BnVxoITO/1038-at020517-verify-user-dropdown-menu-displays-the-operator-logo
> AT_02.05.17 | Verify "User dropdown menu" displays the "Operator Logo"

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/support/utilities/getRandomElementOfArray.js
https://trello.com/c/56E5YuGZ/710-rf-at042809-when-unselecting-the-seat-in-the-seats-table-in-the-summary-section-the-red-color-text-select-seat-appears
> RF | AT_04.28.09 > add getRandomElementOfArray()

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
https://trello.com/c/lpHwA95Y/711-rf-at042901-02-03-add-getarray-getrandomelementofarray-methods
> RF | AT_04.29.01/02/03 > add getArray(), getRandomElementOfArray() methods

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
https://trello.com/c/hU09Cn1z/712-rf-at042803-at042811-at043003-at043001
> RF | AT_04.28.03, AT_04.28.11, AT_04.30.03, AT_04.30.01 > use function getRandomElementOfArray()

- cypress/e2e/testActions/us_AC.05_CreateReservation.cy.js
- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.09_CalendarAvailableDaysWeekUI.cy.js
https://trello.com/c/6XgmqCsC/719-at040907-create-booking-page-departure-date-each-field-has-a-capital-letter-of-the-latin-alphabet
> AT_04.09.07 | Each field has a capital letter of the Latin alphabet

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
- cypress/pageObjects/Header.js
https://trello.com/c/TBqtpMjT/707-at020518-verify-user-dropdown-menu-displays-the-user-role
> AT_02.05.18 | Verify "User dropdown menu" displays the "User Role"

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/xfkKRZ90/697-rf-at042307-verify-email-input-field-has-an-email-text-placeholder
> RF | AT_04.23.07 | Verify email input field has an “Email” text placeholder.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.02_DefaultPageUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/DZPkGlTU/724-at040201-verify-heading-of-the-page-is-create-booking-and-it-is-visible
> AT_04.02.01 | Verify heading of the page is "Create booking" and it is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.26_PassengersDetailsFunc-MultiplePassengers.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/dh1XoGM6/718-at042602-create-booking-page-passengers-details-functionality-multiple-passengers-verify-the-agent-is-able-to-enter-the-second-a
> AT_04.26.02 | Verify the agent is able to enter the second and following passengers name

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
- cypress/support/utilities/getCustomCalendarDay.js
https://trello.com/c/x4Wswfam/714-at041204-verify-tickets-are-not-available-for-the-current-date-gmt7
> AT_04.12.04 | Verify tickets are not available for the current date (GMT+7)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/QPXl6JmM/703-at043103-verify-that-button-reset-is-visible
> AT_04.31.03 | Verify that button “Reset” is visible .

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/GqS97sB9/737-at041602-create-booking-page-departure-on-ui-by-default-selected-date-label-near-departure-on-section-name-has-format-dd-mm-yyyy
> AT_04.16.02 | Selected date label format

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/jZ1OTBsh/744-at041603-create-booking-page-departure-on-ui-by-default-earliest-button-is-selected-visible-and-has-green-background-color-00a65
> AT_04.16.03 | 'Earliest' button is selected, visible and has green background color - rgb(0, 166, 90)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/PJhrGJfy/740-rf-specname-testname
> RF/ US_04_08 Create Booking Page<Departure date>

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/u4W0T6H9/761-rf-us0428-testname
> RF | US_04.28 > divide UI and functional tests into 2 describes

- cypress/e2e/testUiAndFunction/startPage/US_01.11_Header elements.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/j2ETyGEO/732-at011103-start-page-register-agent-account-popup-footer-ui-and-functionality-verify-that-the-x-button-is-visible-in-the-top-righ
> AT_01.11.03 | Verify that the `X button` is visible in the top right corner of the header

- cypress/e2e/testActions/US_AC.01_RegisterNewAgent.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.03_Header_elements.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.04_LoginPopupFooterUIandFn.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.11_Header elements.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.12_FooterUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.18_RestorePasswordPopupFooterUIAndFunc.cy.js
- cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
- cypress/e2e/testUiAndFunction/startPage/us_01.17_HeaderElements.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/C6W7Zkxo/766-rf-startpage-pom
> RF | StartPage POM

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/njz2SqK1/759-at041605-create-booking-page-departure-on-ui-by-default-latest-button-is-unselected-visible-and-has-white-fff-background-color
> AT_04.16.05 | Latest button is visible, unselected, and has white background color

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/jCM2VYep/769-at041606-create-booking-page-departure-on-ui-by-default-latest-button-has-text-latest-in-green-color-00a65a
> AT_04.16.06 | Latest button has text 'Latest' in green color (#00a65a)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
https://trello.com/c/80RZabyQ/699-err-us0408-at040805
> ERR| AT_04.08.05 | Verify previous arrow button switches calendar-week label

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.26_PassengersDetailsFunc-MultiplePassengers.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/nnyyGoWP/742-at042603-create-booking-page-passengers-details-functionality-multiple-passengers-verify-the-agent-is-able-to-select-the-second
> AT_04.26.03 | Verify the agent is able to select the second and following passenger"s fare type

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
https://trello.com/c/QMWfGJpl/701-at042308-verify-passenger-dropdown-is-visible
> AT_04.23.08 | Verify Passenger dropdown is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.27_PassengersDropdownUIandFunc.cy.js
https://trello.com/c/6xK6xgqG/762-at042701-create-booking-page-verify-the-color-of-the-text-in-the-passengers-dropdown-menu
> AT_04.27.01 | Create booking page > Verify the color of the text in the passengers dropdown menu

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.01_SearchSectionUI.cy.js
- cypress/fixtures/bookingsListPage.json
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/iilj9DCz/480-tc050103-booking-list-page-verify-status-dropdown-list-has-values
> AT_05.01.03 | Verify Status dropdown list has values

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/CioW1T5R/775-rf-us0412-add-assert-to-at041204-05-change-tests-order
> RF | US_04.12 > add assert to AT_04.12.04/05, change tests order

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.27_PassengersDropdownUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/header/US_02.01_leftLogoUIandFunc.cy.js
- cypress/pageObjects/Header.js
https://trello.com/c/rliGfkiI/779-at020103-header-left-logo-ui-and-functionality-verify-background-color-is-00a65a
> AT_02.01.03 | Verify background color is #00a65a

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.25_functionality-One passenger.cy.js
https://trello.com/c/qJXfiv0s/666-at042503-verify-agent-is-able-to-choose-main-passenger-fare-type-from-fare-type-dropdown-menu
> AT_04.25.03 | Verify agent is able to choose main passenger fare type from 'Fare type' dropdown menu

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.27_PassengersDropdownUIandFunc.cy.js
https://trello.com/c/6FbUfXmt/783-rf-us0427
> RF | US_04.27

- cypress/e2e/testUiAndFunction/startPage/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
https://trello.com/c/jESggAvd/745-at010208-start-page-login-register-section-link-register-account-now-color-green
> AT_01.02.08 | Link 'Register account now': color "green"

- cypress/e2e/testActions/us_AC.05_CreateReservation.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/jHvDEPQz/784-rf-usac05
> rf_US_AC.05

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/XSszrMoO/787-rf-us0412-add-force-true
> RF | US_04.12 > add {force: true}

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js
https://trello.com/c/Laq3V5e5/786-rf-ac042202-verify-trip-card-are-sorted-from-latest-to-earliest-time-if-latest-button-is-clicked
> RF | AT_04.22.02 

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
TC -   https://trello.com/c/yJ2VsrLG/798-tc040502-departure-arrival-block-ui-verify-that-the-departure-station-label-has-color-666
AT  - https://trello.com/c/qpr6kpb1/799-at040502-departure-arrival-block-ui-verify-that-the-departure-station-label-has-color-666
> AT_04.05.02 | Verify that the Departure station label has color #666

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
TC - https://trello.com/c/wfDYab3C/800-tc040503-departure-arrival-block-ui-verify-that-the-departure-station-dropdown-menu-has-input-select-search-field
AT - https://trello.com/c/vpe1mzOC/801-at040503-departure-arrival-block-ui-verify-that-the-departure-station-dropdown-menu-has-input-select-search-field
> AT__04.05.03 Verify that the Departure station dropdown menu has Input select-search field.

- cypress/e2e/testUiAndFunction/startPage/US_01.14_Register_UI.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/Rg9WwYbg/805-at011401-verify-that-the-label-your-name-is-visible-in-the-modal-body-has-the-666-color-and-font-size-14px
> AT_01.14.01 | Verify that the label "Your name" is visible in the modal body, has the #666 color and font size: 14px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/Z8gswq91/808-rf-us0412-at041204-at041205
> RF | US_04.12 > AT_04.12.04, AT_04.12.05

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.01_MultilanguageSectionElements.cy.js
https://trello.com/c/xxiQrnRA/244-at010104-verify-thailand-flag-icon-clickable-changing-language-to-thai
> AT_01.01.04 | Verify Thailand flag icon: clickable / changing language to Thai

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/10BaASgL/771-at040807-create-booking-page-departure-date-verify-that-back-arrow-click-doesnt-show-elapsed-week
> AT_04.08.07|  Verify that back arrow click doesn't show elapsed week

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.01_SearchSectionUI.cy.js
https://trello.com/c/OoqbjkAl/813-rf-us0501-at050101
> RF | US_05.01 > AT_05.01.01

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.01_SearchSectionUI.cy.js
> "RF | US_05.01 > AT_05.01.01" Restore

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/pP661Cve/819-at042204-trip-cards-are-filtered-by-vehicle-class-vip-bus-24-selected-from-trip-class-dropdown-menu
> AT_04.22.04 | Trip cards are filtered by vehicle class "VIP bus 24" selected from trip class dropdown menu

- cypress/e2e/testUiAndFunction/createBookingPage/us_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/7TwdZRk1/794-at042309-verify-passenger-dropdown-has-1-passenger-by-default
> AT_04.23.09 | Verify Passenger dropdown has 1 passenger by default

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.26_PassengersDetailsFunc-MultiplePassengers.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.07_LoginByEmailTab_negative.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/F59gRR8D/821-at042604-create-booking-page-passengers-details-functionality-multiple-passengers-verify-that-only-one-passenger-is-removed-by-c
> AT_04.26.04 | Verify that only one passenger is removed by clicking the "Remove passenger" button

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/qfMMouLN/830-at040506-departure-arrival-station-departure-arrival-block-ui-verify-that-the-arrival-station-label-has-color-666666
> AT_04.05.06 | Departure/arrival station > Departure / Arrival block UI > Verify that the 'Arrival station' label has color - #666

- cypress/e2e/testUiAndFunction/startPage/US_01.10_LoginByPhoneNegative.cy.js
- cypress/fixtures/startPage.json
- cypress/pageObjects/StartPage.js
https://trello.com/c/6XkA73Xz/835-at011004-login-by-phone-negative-registering-is-not-possible-with-any-letters-phone-number-input
> AT_ 01.10.04 | Registering is not possible with any letters in 'Phone number' input

- cypress/e2e/testUiAndFunction/startPage/US_01.07_LoginByEmailTab_negative.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/d8TYwJnK/837-rf-err-us0107-at010702-verify-the-error-message-after-click-sign-in-with-an-invalid-email
> RF | AT_01.07.02 | Verify the error message after click Sign In with an invalid email

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js
- cypress/support/utilities/sortArrayByDigit.js
https://trello.com/c/PJYOIjPp/841-rf-at042202-at041607
> RF | AT_04.22.02, AT_04.16.07 > move sort function to utilities 

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/beuQYpNU/760-at042801the-section-name-seat-selection-is-visible
> AT_04.28.01|The section name "Seat selection" is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/LFWXgoza/847-at043008-verify-total-price-for-one-passenger-for-each-fare-type-elder-child-adult-matches-price-displayed-on-trip-card
> AT_04.30.08 | Verify total price for one passenger for each fare type (Elder, Child, Adult) matches expected price

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/6TR4UBra/826-at040504-verify-that-the-departure-station-label-has-font-15px-sans-serif
> AT_04.05.04 | Verify that the Departure station label has font - 15px sans-serif

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/ePGJRj0S/856-at043009-verify-total-price-for-ticket-for-one-passenger-for-each-fare-type-elder-child-adult-matches-expected-price
> AT_04.30.09 | Verify total price for ticket for one passenger for each fare type (Elder, Child, Adult) matches expected price

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
https://trello.com/c/hsIhaeMu/446-at050303-verify-that-the-calendar-dropdown-is-displayed
> AT_05.03.03 | Verify that the "calendar" dropdown is displayed

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/EX2bCdsL/848-rf-at042812
> RF | AT_04.28.12 > replacing the random selection of the number of passengers with the selection of the boundary values

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/SJlOAMyk/864-at043106-verify-book-tickets-has-a-background-color-00a65a-and-color-of-the-text-fff
> AT_04.31.06 | Verify that button “Book tickets” has a background color (#FFF) after navigating on it.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.26_PassengersDetailsFunc-MultiplePassengers.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/DaZIEXkg/858-at042605-create-booking-page-passengers-details-functionality-multiple-passengers-verify-all-info-about-main-passenger-is-not-de
> AT_04.26.05 | Verify all info about main passenger is not deleted after selecting different number of passengers

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/iSusEofv/816-at042312-verify-notes-remark-label-is-present-and-visible
> AT_04.23.12 | Verify "Notes/Remark" label is present and visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/SSg3zdXt/874-at043108-verify-that-dropdown-toggle-button-is-visible
> AT_04.31.08 | Verify that dropdown-toggle button is visible.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/HQJnMuw1/875-at043107-verify-that-the-dropdown-toggle-button-has-color-fff
> AT_04.31.07 | Verify that the dropdown-toggle button has color (#FFF)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.17_DepartureOnTripSelectedUI.cy.js
- cypress/fixtures/colors.json
- cypress/fixtures/createBookingPage.json
https://trello.com/c/XJqvr0T7/839-at041701-verify-selected-date-label-has-text-color-00a65a-background-color-edf8ed-font-size-150
> AT_04.17.01 | Verify "Selected Date" label has text color #00a65a, background-color #edf8ed, font-size: 150%

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.23_TripDetailsUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/F8wWHNLp/879-at043109-verify-that-the-pop-up-button-reserve-tickets-is-visible
> AT_04.31.09 | Verify that the pop up button “Reserve tickets” is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.26_PassengersDetailsFunc-MultiplePassengers.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/hoXSB2X4/882-rf-us0426-at042605
> RF | US_04.26 > AT_04.26.05

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/fmijTEgT/890-rf-0428-change-context-to-describe-and-add-intercepts
> RF | 04.28 > Change context to describe and add intercepts

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.18.01_SelectedTripCard.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/2jAamTa3/895-at041801-create-booking-page-selected-trip-card-ui-number-available-tickets-trip-card-is-visible-selected-and-background-color-i
> AT_04.18.01 | "Number available tickets" trip card is visible, selected, and background color is green(rgb(0, 166, 90))

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/pFTOLnwz/897-rf-at042803
> RF | AT_04.28.03

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/PfgrUvcD/894-rf-at043109-verify-that-the-pop-up-button-reserve-tickets-is-visible
> RF | AT_04.31.09 > Verify that the pop up button “Reserve tickets” is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.18.01_SelectedTripCard.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/EX2bCdsL/848-rf-at042812-replacing-the-random-selection-of-the-number-of-passengers-with-the-selection-of-the-boundary-values
> RF | AT_04.28.12

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/GsIk589W/901-rf-at043001-at043003
> RF | AT_04.30

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
- cypress/fixtures/colors.json
https://trello.com/c/1iSEYjK4/885-at043110-verify-that-the-pop-up-button-reserve-tickets-has-a-background-color-f4f4f4
> AT_04.31.10 | Verify that the pop-up button “Reserve tickets” has a background color (#f4f4f4).

- cypress/e2e/testUiAndFunction/startPage/US_01.14_Register_UI.cy.js
https://trello.com/c/UH2g3ut5/906-at011402-section-sections-unititem
> AT_01.14.02 |  Verify that the example(placeholder) "John Doe" is visible in the name field, has the #666 color, and font size: 14px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
TC -  https://trello.com/c/VKA32MuZ/907-tc043010-summary-ui-text-total-is-displayed-and-visible
AT - https://trello.com/c/EXg2FUyl/908-at043010-summary-ui-text-total-is-displayed-and-visible
> AT_04.30.10 | Text "Total" is displayed and visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/im80aQeP/919-rf-at042802-at042809-remove-random
> RF | AT_04.28.02, AT_04.28.09 > remove random

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
https://trello.com/c/HGtMrs44/920-rf-at042903-remove-random
> RF | AT_04.29.03 > remove random

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.02_DefaultPageUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/UfKtB0Hi/922-at040202-verify-departure-arrival-station-section-exists-is-visible
> AT_04.02.02 | Verify Departure/Arrival station section exists/is visible

- cypress/e2e/testUiAndFunction/header/US_02.05_UserDropdownMenuUIAndFunc.cy.js
https://trello.com/c/xzhc5ctm/917-rf-us0205-change-context-to-describe
> RF | US_02.05 > Change context to describe

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.02_DefaultPageUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/fru52wo4/925-at040203-verify-section-has-a-label-arrival-station-and-it-is-visible
> AT_04.02.03 | Verify section has a label "Arrival station" and it is visible.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.02_DefaultPageUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/SdZPqme5/926-at040204-verify-section-has-a-label-departure-station-and-its-visible
> AT_04.02.04 | Verify section has a label "Departure station" and it is visible

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.12_FilterColumnsFunc.cy.js
https://trello.com/c/p6jevfTi/939-rf-us0512-change-context-to-describe
> RF | US_05.12 > Change context to describe

- cypress/e2e/testUiAndFunction/startPage/US_01.13_RegisterFunctionality.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/5YXzzW0Z/913-tc011301-start-page-register-functionality-register-button-is-clickble
> AT_01.13.01 | Register button is clickble

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.26_PassengersDetailsFunc-MultiplePassengers.cy.js
https://trello.com/c/1LQiHabU/942-rf-us0426-change-context-to-describe
> RF | US_04.26 > Change context to describe

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.31_TotalUI.cy.js
https://trello.com/c/9PHmf8ZY/944-rf-at041204-at041204
> RF | AT_04.12.04, AT_04.12.04

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
https://trello.com/c/imZoBVGd/943-rf-us0430-change-context-to-describe
> RF | US_04.30 > Change context to describe

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.14_Week button elements view UI.cy.js
TC - https://trello.com/c/J3WgeANG/950-tc041401-week-button-elements-view-in-the-upper-left-corner-of-the-section-there-is-a-label-departure-date-which-has-the-color-6
AT - https://trello.com/c/suTZeXL5/951-at041401-week-button-elements-view-in-the-upper-left-corner-of-the-section-there-is-a-label-departure-date-which-has-the-color-6
> AT_04.14.01 | In the upper left corner of the section there is a label Departure date which has the color #666666

- cypress/e2e/testUiAndFunction/startPage/US_01.14_Register_UI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/NWtN6jZ1/910-at011403-verify-that-the-label-company-name-is-visible-in-the-modal-body-has-the-999-color-and-font-size-14px
> AT_01.14.03 | Verify that the label "Company name" is visible in the modal body, has the #999 color and font size: 14px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
https://trello.com/c/qna2E9h4/954-at042405-verify-email-input-field-has-an-email-text-placeholder
> AT_04.24.05 | Verify email input field has an “Email” text placeholder.

- cypress/e2e/testUiAndFunction/startPage/US_01.14_Register_UI.cy.js
https://trello.com/c/PQeqFg1H/959-at011404-verify-that-the-exampleplaceholder-john-doe-is-visible-in-the-name-field-has-the-666-color-and-font-size-14px
> AT_01.14.04 | Verify that the example(placeholder) 'John Doe' is visible in the name field, has the #666 color, and font size: 14px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
- cypress/pageObjects/CreateBookingPage.js
- cypress/support/utilities/ifLeapYear.js
https://trello.com/c/vbEgGUxt/935-err-at041602-date-error
> ERR | AT_04.16.02

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
https://trello.com/c/VpHK2D7m/936-err-at041505
https://trello.com/c/feYLzPVY/937-err-at041507
> ERR | AT_04.15.05,  ERR | AT_04.15.07 are fixed

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/4cRcZkMM/887-at040505-verify-that-the-departure-station-label-has-margin-0px-0px-5px
> AT_04.05.05 | Verify that the Departure station label has margin - 0px 0px 5px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.19_UnselectedTripCardAvailable.cy.js
https://trello.com/c/kvUrjQC4/970-at041902-create-booking-page-unselected-trip-card-available-ui-verify-background-color-of-trip-card-is-white-fff
> AT_04.19.02 | Verify Background color of Trip cards is white (#FFF)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.02_DefaultPageUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/XdIdJCrk/976-at040206-verify-section-title-is-departure-date-and-it-is-visible
> AT_04.02.06 | Verify section title is "Departure date" and it is visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.09_CalendarAvailableDaysWeekUI.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
https://trello.com/c/TAoJAdSZ/986-err-us0412-at041202
> RF | Err AT_04.12.02

- cypress/e2e/testUiAndFunction/startPage/US_01.14_Register_UI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/Ufrhch6N/974-at011405-verify-that-the-label-company-name-is-visible-in-the-modal-body-has-the-999-color-and-font-size-14px
> AT_01.14.05 | Verify that the label "Email" is visible in the modal body, has the #999 color and font size: 14px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/7N1EcwDK/967-err-at043001
https://trello.com/c/2AxSlpQf/968-err-at043003
> RF | US_04.30 

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.29_SeatSelectionDropdownUIandFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/RFKh3CU3/1002-rf-us0429
> RF | US_04.29

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
https://trello.com/c/3hxekKAF/1003-rf-us0428
> RF | US_04.28

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.19_UnselectedTripCardAvailable.cy.js
- cypress/fixtures/colors.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/un9gZWWR/997-at041903-create-booking-page-unselected-trip-card-available-ui-verify-class-name-is-bus-or-ferry-name-in-a-dark-gray-color-4b4b4
> AT_04.19.03 | Verify "Class name" is bus or ferry name in a dark gray color (#4B4B4B) and visible below Departure time

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
- cypress/fixtures/createBookingPage.json
TC - https://trello.com/c/lmJOOBCc/1006-tc040508-departure-arrival-block-ui-verify-that-the-arrival-station-label-has-font-15px-sans-serif-and-margin-0px-0px-5px
AT - https://trello.com/c/K9BxEIRv/1007-at040508-departure-arrival-block-ui-verify-that-the-arrival-station-label-has-font-15px-sans-serif-and-margin-0px-0px-5px
> AT_04.05.08 |Verify that the "Arrival station" label has font - 15px sans-serif and  margin - 0px 0px 5px

- cypress/e2e/testUiAndFunction/startPage/US_01.14_Register_UI.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/N5DOjAdD/1009-at011407-verify-that-the-label-email-is-visible-in-the-modal-body-has-the-999-color-and-font-size-14px
> AT_01.14.07 | Verify that the label "Phone number" is visible in the modal body, has the #999 color and font size: 14px

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/sjWlyyEw/966-at042314-verify-fare-type-selection-arrow-is-present-and-visible
> AT_04.23.14 | Verify Fare type selection arrow is present and visible

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.02_DefaultPageUI.cy.js
https://trello.com/c/0yMt4zew/1020-at040209-create-booking-page-verify-passenger-details-section-exists-is-visible
> AT_04.02.09 | Create booking page >Verify Passenger details section exists/is visible.

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
- cypress/fixtures/startPage.json
https://trello.com/c/MaGCxuRR/1012-at010816-start-page-login-pop-up-verify-request-code-button-has-text-request-code
> AT_01.08.16 | Verify `REQUEST CODE` button has text REQUEST CODE

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
https://trello.com/c/WGqRFESB/981-at042406-verify-phone-number-input-field-has-a-phone-number-text-placeholder
> AT_04.24.06 | Verify phone number input field has a “Phone number” text placeholder.

- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/fjMuzucP/1016-at010817-start-page-login-pop-up-verify-request-code-button-has-border-color-6ccd66
> AT_01.08.17 | Start page > Login pop-up > Verify `REQUEST CODE` button has border-color - #6CCD66

- cypress/e2e/testUiAndFunction/startPage/US_01.04_LoginPopupFooterUIandFn.cy.js
- cypress/e2e/testUiAndFunction/startPage/US_01.08_LoginByPhoneNumberTabUI.cy.js
https://trello.com/c/TUmFpMHx/1010-at010405-login-popup-footer-verify-the-agent-is-able-to-click-on-the-forgot-your-password-link-in-the-footer
> AT_01.04.05 | Login Popup < Footer < Verify the Agent is able to click on the Forgot your password link in the footer

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/onZjseXr/1022-tc040811-create-booking-page-departure-date-verify-that-month-format-label-is-oct-2023
> AT_04.08.11 | Verify that month format label is "Oct 2023"

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/1VUk3WQs/1027-rf-us0428-at042807
> RF | US_04.28 > AT_04.28.07

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/BookingsListPage.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/MajMWqDb/1018-at050201-verify-that-the-agent-is-able-to-enter-data-in-search-input-field-and-find-booking
> AT_05.02.01 | Verify that the agent is able to enter data in Search input field and find booking

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/gbvMBSVK/1029-err-at043001
https://trello.com/c/O0UQD1KX/1031-rf-specname-testname
> RF | ERR _US_04.30

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/MQkjJRFg/881-at040507-verify-that-the-departure-station-dropdown-menu-has-selection-arrow
> AT_04.05.07 | Verify that the Departure station dropdown menu has 'Selection arrow'

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/BookingPopup.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/qTM0apTm/1033-at050202-verify-that-the-agent-is-able-to-enter-data-in-booking-id-input-field-and-find-booking
> AT_05.02.02 | Verify that the agent is able to enter data in Booking ID input field and find booking

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/btX1bPHX/1043-rf-at050201-02
> RF | AT_05.02.01/02

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/090j6Cah/1025-at040812-create-booking-page-departure-date-verify-that-week-format-label-is-2-oct-8-oct
> AT_04.08.12 | Verify that week format label is "2 Oct - 8 Oct"

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/e2e/testUiAndFunction/createBookingPage/US_04.30_SummaryUI.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/VcxV1KKz/1046-rf-specname-testname
> RF | AT_04.30.05

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/nMIzPGxL/1048-rf-specname-testname
> RF | US_04.22 

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js
https://trello.com/c/RGdEWM2J/998-at042407-verify-passenger-name-input-field-has-a-passenger-name-text-placeholder
> AT_04.24.07 | Verify passenger name input field has a “Passenger name” text placeholder

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.25_functionality-One passenger.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
[https://trello.com/c/fCsgCdqn/1057-tc042504-create-booking-page-verify-email-input-field-doesnt-accept-invalid-emails-and-system-displays-alert](url)
> AT_04.25.04 | Verify email input field doesnt accept invalid emails and system displays alert.

- cypress/e2e/testUiAndFunction/startPage/US_01.13_RegisterFunctionality.cy.js
https://trello.com/c/mhOtDYwb/1056-at011302-start-page-register-functionality-close-popup-window-clickable-click-on-x
> AT_01.13.02 | Close popup window clickable (click on X)

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/fW7YD6aU/938-err-at041202
> RF | AT _04.12.02 

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/yXOmD2cg/1060-rf-specname-testname
> RF | AT_04.08.05

- cypress/e2e/testActions/US_AC.04_CreateBooking.cy.js
https://trello.com/c/HkvyODen/1063-atac0403-actions-create-booking-for-2-passengers-elder-elder
> AT_AC.04.03 | Create booking for 2 passengers: Elder + Elder

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/3PueXewJ/1070-rf-removing-duplicate-method-in-bookingslistpage
> RF | Removing duplicate method in BookingsListPage

- cypress/e2e/testUiAndFunction/startPage/us_01.06_LoginByEmailTub.cy.js
https://trello.com/c/FRCuH6JZ/4-rf-specname-testname
> RF | AT_01.06.01 | Sign In Button redirect to the Create Booking Page

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
[RF | AT_04.12.04/05](https://trello.com/c/3wOFpjOY/1079-rf-at041204-05)
> RF | AT_04.12.04/05 > removing duplicate lines of code

- cypress/e2e/testUiAndFunction/startPage/US_01.18_RestorePasswordPopupFooterUIAndFunc.cy.js
https://trello.com/c/wJwgZ7tK/1074-at011802-start-page-restore-password-popup-verify-the-text-no-account-yet-has-rgb153-153-153-color-and-14px-font-size
> AT_01.18.02  | Verify the text “No account yet?” has rgb(153, 153, 153) color and 14px font-size'

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/btX1bPHX/1043-rf-at050201-02
> RF | AT_05.02.01/02 > add assertion

- cypress/e2e/testUiAndFunction/startPage/US_01.18_RestorePasswordPopupFooterUIAndFunc.cy.js
https://trello.com/c/WMw3sGET/1076-at011803-start-page-restore-password-popup-verify-the-link-register-has-rgb66-139-202-color-and-14px-font-size
> AT_01.18.03 | Verify the link “Register” has rgb(66, 139, 202) color and 14px font-size

- cypress/e2e/testUiAndFunction/startPage/US_01.18_RestorePasswordPopupFooterUIAndFunc.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/GfmUBmUZ/1078-at011804-start-page-restore-password-popup-verify-the-link-login-has-rgb66-139-202-color-and-14px-font-size
> AT_01.18.04 | Verify the link “login” has rgb(66, 139, 202) color and 14px font-size

- cypress/e2e/testUiAndFunction/startPage/US_01.18_RestorePasswordPopupFooterUIAndFunc.cy.js
- cypress/pageObjects/StartPage.js
https://trello.com/c/UIYeVMap/1084-rf-at011802-at011803
> RF | AT_01.18.02 / AT_01.18.03

- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.04_DateFilterFunctionality.cy.js
- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.10_ExcelButtonUIandFunc.cy.js
- cypress/pageObjects/BookingsListPage.js
https://trello.com/c/ypEJSUkG/1083-at050405-verify-calendar-dates-are-correct-if-clicking-on-corresponding-date-from-date-range-dropdown-menu
> AT_05.04.05 | Verify calendar dates are correct if choosing corresponding date from date range dropdown menu

- cypress/e2e/testActions/US_AC.08_ExtendReservation.cy.js
- cypress/e2e/testUiAndFunction/bookingsListPage/US_05.02_SearchSectionFunctionality.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/BookingPopup.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/id35fM4G/1035-atac0801-actions-extend-reservation-extend-one-time-and-verify-the-time-counter-in-the-text-field-this-reservation-will-expire-i
> AC.08.01 Extend timer

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.32_TotalFunctionality.cy.js
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/YW6DjRJr/550-at043201-verify-that-the-reset-button-is-clickable
> AT_04.32.01 | Verify that the "Reset" button is clickable.

- cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js
- cypress/fixtures/createBookingPage.json
- cypress/pageObjects/CreateBookingPage.js
https://trello.com/c/IKuqwP0x/1090-tc042815-the-title-of-seats-table-is-visible-and-matches-to-the-class-of-the-selected-trip-ferry
> AT_04.28.15 | The title of "Seats table" is visible and matches to the class of the selected trip "Ferry"

- cypress/e2e/testActions/US_AC.04_CreateBooking.cy.js
- cypress/fixtures/createBookingPage.json
https://trello.com/c/33qEm7hN/1132-atac0404-actions-create-booking-for-2-passengers-adultchild
> AT_AC.04.04 | Actions >Create booking for 2 passengers: Adult+Child

- cypress/e2e/testBookingReservation/Booking/CB_1.cy.js
- cypress/fixtures/bookingPopup.json
- cypress/pageObjects/BookingPopup.js
https://trello.com/c/bCtg2Yd4/1163-atcb116-verify-the-number-seat-is-equel
> CB_1.16 | Verify the number Seat is equel

- cypress/e2e/testBookingReservation/Booking/CB_1.cy.js
- cypress/fixtures/bookingPopup.json
- cypress/pageObjects/BookingPopup.js
https://trello.com/c/r6d9Sndg/1166-atcb117-verify-message-to-operator-is-exists
> CB_1.17 | Verify Message to operator is exists

- cypress/e2e/testBookingReservation/Booking/CB_3.cy.js
- cypress/pageObjects/BookingPopup.js
https://trello.com/c/0ulbu7Uf/1201-at0cb309-verify-that-the-booking-ticket-has-the-correct-contact
> CB_3.09 | Verify that the booking ticket has the correct Contact

- cypress/e2e/testBookingReservation/Booking/CB_1.cy.js
- cypress/pageObjects/BookingPopup.js
https://trello.com/c/wX0lJvsH/1176-atcb118-verify-after-clicking-message-to-operator-opens-new-popup-start-a-discussion-with-qa-test-op-about-booking
> AT_CB_1.18 | Verify after clicking Message to operator opens new popup Start a discussion with QA Test OP about booking

- cypress/e2e/testBookingReservation/Booking/CB_3.cy.js
- cypress/pageObjects/BookingPopup.js
https://trello.com/c/GyetsSdX/1195-atcb310-verify-that-the-booking-ticket-has-the-correct-price
> CB_3.10 | Verify that the booking ticket has the correct Price

- cypress/e2e/testBookingReservation/Booking/CB_3.cy.js
https://trello.com/c/mgCF3CLx/1213-atcb313-verify-that-the-booking-ticket-has-the-correct-status
> CB_3.13 | Verify that the booking ticket has the correct Status
