RedRoverSchool/BookingProject

cypress/e2e/testUiAndFunction/startPage/loginRegisterSection/US_01.02_LoginRegisterSectionElementsUIandFunc.cy.js
cypress/fixtures/startPage/links.json

https://trello.com/c/0OJSGBcy/148-at010201-start-page-verify-link-register-account-now-visible-and-have-text-register-account-now

AT_01.02.01 | Start page > Verify Link 'Register account now': visible and have text 'Register account now'

---

cypress/e2e/testUiAndFunction/startPage/loginPopupSection/US_01.07_LoginByEmailTab_negative.cy.js
cypress/fixtures/startPage/alert.json
cypress/pageObjects/StartPage.js

https://trello.com/c/C5jy7Cce/263-at010701-login-by-email-tab-negative-verify-error-message-after-click-signin-with-empty-login-fields

AT_01.07.01 | Login by email tab negative > Verify error message after click SignIn with empty login fields

---

cypress/e2e/testUiAndFunction/createBookingPage/departureDateSection/US_04.11_CalendarWeekFunc.cy.js

[AT_04.11.01 | Create booking page > Deparure date > Calendar week functionality >Verify that you can click on last date field if it has not expired](https://trello.com/c/PT2O6TEU/186-at041101-create-booking-page-deparure-date-calendar-week-functionality-verify-that-you-can-click-on-any-date-field-if-it-has-not)

AT_04.11.01 | Create booking page > Deparure date > Calendar week functionality >Verify that you can click on last date field if it has not expired

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js

https://trello.com/c/TZ8AFmml/261-at041302-verify-that-the-first-option-of-the-month-dropdown-menu-has-the-current-month-and-the-current-year

AT_04.13.02 | Verify the first option of the Month dropdown menu has the current month and the current year

---

cypress/e2e/testUiAndFunction/startPage/US_01.05_LoginByEmailTab_UI.cy.js
cypress/fixtures/startPage.json
cypress/pageObjects/StartPage.js

https://trello.com/c/7ZU6tQnJ/342-at010502-login-by-email-tab-ui-insure-email-label-text-is-email
AT_01.05.02 | Login by email tab UI > Insure Email label text is 'Email'

AT_01.05.02 | Login by email tab UI > Insure Email label text is 'Email'

---

cypress/e2e/testUiAndFunction/startPage/us_01.15_RegisterAgentNegative.cy.js
cypress/fixtures/startPage.json

https://trello.com/c/7naOM4mF/366-at011507-start-page-register-agent-negative-error-message-is-displayed-when-trying-to-register-with-previously-used-email

AT_01.15.07 | Error message is displayed when trying to register with previously used email

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.13_MonthDropdownMenu.cy.js
cypress/support/utilities/createArrayOfMonths.js

https://trello.com/c/u1bW8GXH/365-at041304-verify-month-dropdown-menu-has-13-consecutive-months-and-year-options-starting-from-current-month-and-year

AT_04.13.04 | Verify month dropdown menu has 13 consecutive months and year options starting from current month and year

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js

https://trello.com/c/UV5LO8rO/506-err-us0412-calendar-month-functionality-at041201-create-booking-page-verify-any-date-earlier-than-the-current-date-is-not-availa

ERR | US_04.12 | Calendar month functionality > AT_04.12.01 | Create booking page > Verify any date earlier than the current date is not available

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js

[RF |AT_04.11.03 |Verify that if the date has expired, then the field with it is not clickable]|(https://trello.com/c/qaCsya6G/507-rf-at041103-create-booking-page-deparure-date-calendar-week-functionality-verify-that-if-the-date-has-expired-then-the-field-wit)

RF |AT_04.11.03 |Verify that if the date has expired, then the field with it is not clickable

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.07_ArrivalDropdown.cy.js
cypress/pageObjects/CreateBookingPage.js

TC - https://trello.com/c/WqsG9bRy/346-tc040702-create-booking-page-arrival-dropdown-ui-and-functionality-verify-that-after-clicking-on-any-space-outside-of-the-opened
AT - https://trello.com/c/84ZsFNkP/347-at040702-create-booking-page-arrival-dropdown-ui-and-functionality-verify-that-after-clicking-on-any-space-outside-of-the-opened

AT_04.07.02_Verify that after clicking on any space outside of the opened drop-down menu, the drop-down menu will close.

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
cypress/fixtures/createBookingPage.json

https://trello.com/c/BaNweIsK/561-at041502-create-booking-page-month-button-elements-view-while-the-month-button-is-selected-the-week-button-does-not-have-the-att

AT_04.15.02 | While selected Month button, the Week button does not have the attribute "selected" and its background color is rgb(255, 255, 255)

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js

https://trello.com/c/x2sky98e/515-err-us0412calendarmonthfunc-at041201-create-booking-page-verify-any-date-earlier-than-the-current-date-is-not-available

ERR | US_04.12_CalendarMonthFunc > AT_04.12.01 | Create booking page > Verify any date earlier than the current date is not available

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js
cypress/fixtures/createBookingPage.json

https://trello.com/c/42qAs70L/568-rf-at041103verify-that-if-the-date-has-expired-then-the-field-with-it-is-not-clickable

RF_AC_04.11.03 | Verify that if the date has expired, then the field with it is not clickable

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js
cypress/pageObjects/CreateBookingPage.js

https://trello.com/c/2qEByZiK/576-at041503-create-booking-page-month-button-elements-view-month-dropdown-menu-to-the-left-of-the-week-button-is-visible-and-availa

AT_04.15.03 | Month dropdown menu is visible and available only after the Month button is chosen

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js

https://trello.com/c/BGHPYEmj/596-at041505-create-booking-page-month-button-elements-view-calendar-label-between-arrows-is-visible-and-its-format-has-the-name-of

AT_04.15.05 | Calendar label is visible and its format has the name of the current month and year

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.15_MonthBtnElementsView.cy.js

https://trello.com/c/LwrhZzb2/656-at041506-create-booking-page-month-button-elements-view-calendar-day-selection-block-under-the-calendar-label-is-visible-and-has

AT_04.15.06 | Calendar-day-selection bloc

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.05_DepartureArrivalBlockUI.cy.js
cypress/pageObjects/CreateBookingPage.js

https://trello.com/c/VUigWB4i/709-at040501-verify-that-the-departure-station-label-is-displayed-visible-and-is-not-changeably

AT_04.05.01 | Verify that the Departure station label is displayed, visible, and is not changeably.

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js

https://trello.com/c/GVoLCQS3/717-at041205-tickets-are-not-available-for-tomorrow-the-current-date-by-gmt7

AT_04.12.05 | Tickets are not available for tomorrow (the current date by GMT+7)

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js
cypress/fixtures/createBookingPage.json

https://trello.com/c/GZXref9i/754-at041604-create-booking-page-departure-on-ui-by-default-earliest-button-has-text-earliest-in-white-color-fff-rgb255-255-255

AT_04.16.04 | 'Earliest' button has text 'Earliest' in white color rgb(255, 255, 255)

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.11_CalendarWeekFunc.cy.js

[RF_04.11.05 |Verify that when you click an invalid date in the Departure on, the date doesn't change](https://trello.com/c/hu4mTY2L/785-rfat041105-create-booking-page-deparure-date-calendar-week-functionality-verify-that-when-you-click-an-invalid-date-in-the-depar)

RF_04.11.05 |Verify that when you click an invalid date in the Departure on, the date doesn't change

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.08_CalendarSelectionBlockUIandFunk.cy.js
cypress/e2e/testUiAndFunction/createBookingPage/US_04.28_SeatSelectionUIandFunc.cy.js

https://trello.com/c/r7a9eBfJ/780-at040808-calendar-selection-block-functionality-week-month-view-verify-that-back-arrow-click-doesnt-show-elapsed-month

AT_04.08.08 | Verify that back arrow click doesn't show elapsed month

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.12_CalendarMonthFunc.cy.js
cypress/e2e/testUiAndFunction/createBookingPage/US_04.16_DepartureOnDefault.cy.js

https://trello.com/c/i0A0YDnj/774-at041607-trip-cards-are-sorted-by-time-of-departure-from-earliest-to-latest-by-default

AT_04.16.07 | Trip cards are sorted by time of departure from earliest to latest by default

---

cypress/e2e/testUiAndFunction/startPage/US_01.07_LoginByEmailTab_negative.cy.js
cypress/fixtures/startPage.json
cypress/pageObjects/StartPage.js

https://trello.com/c/OE0oCfPX/817-at010702-start-page-login-popup-login-by-email-tab-negative-verify-the-error-message-after-click-sign-in-with-an-invalid-email

AT_01.07.02 |  AT_01.07.02 | Start page > Verify the error message after click Sign In with an invalid email

---

cypress/e2e/testUiAndFunction/startPage/US_01.10_LoginByPhoneNegative.cy.js
cypress/fixtures/startPage.json

https://trello.com/c/1eWyUKiE/832-at011003-login-by-phone-negative-registering-is-not-possible-with-any-letters-country-code-input

AT_01.10.03 | registering is not possible with any letters 'Country code' input

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js

https://trello.com/c/7yuAsx1n/824-at042206-create-booking-page-departure-on-after-clicking-on-the-earliest-tab-user-should-the-earliest-available-trip-on-a-left

AT_04.22.06 | Verify when after clicking on the "Earliest" tab, user should the earliest available trip on a left'

---

cypress/e2e/testUiAndFunction/startPage/US_01.20_RestorePasswordPopupNegative.cy.js
cypress/fixtures/startPage.json
cypress/pageObjects/StartPage.js

https://trello.com/c/1fGcmoYI/846-at012001-start-page-restore-password-popup-verify-that-the-user-is-not-able-to-restore-the-password-with-empty-email-input

AT_01.20.01 | Verify that the user is not able to restore the password with empty Email input

---

cypress/e2e/testUiAndFunction/startPage/US_01.20_RestorePasswordPopupNegative.cy.js
cypress/fixtures/startPage.json

https://trello.com/c/xKNHOYrH/853-at012003-start-page-restore-password-popup-verify-that-the-error-message-wrong-email-is-displayed-with-two-signs-at-the-email-in

AT_01.20.03 | Start Page > Restore password Popup > Verify that the error message ‘Wrong email’ is displayed with two @ signs at the ‘Email’ input

---

cypress/e2e/testUiAndFunction/bookingsListPage/US_05.03_DateFilterUI.cy.js
cypress/pageObjects/BookingsListPage.js

https://trello.com/c/Q8PUWMyk/854-rf-050302-date-filter-ui-verify-that-the-calendar-dropdown-has-defaulted-to-the-current-date-in-format-dd-mmm-yyyy

RF | 05.03.02| Verify that the "calendar" dropdown has defaulted format DD MMM, YYYY

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.23_PassengersDetailsDefaultUI.cy.js

https://trello.com/c/CH8b0Wyq/863-at042313-verify-fare-type-has-adult-option-displayed-by-default

AT_04.23.13 | Verify Fare type has “Adult” option displayed by default.

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js
cypress/pageObjects/CreateBookingPage.js

https://trello.com/c/O9DqME7h/883-rf-at042206-verify-when-after-clicking-on-the-earliest-tab-user-should-the-earliest-available-trip-on-a-left

RF | AT_04.22.06 | Verify when after clicking on the "Earliest" tab, user should the earliest available trip on a left

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.24_Multiple_passengers_UI.cy.js

https://trello.com/c/Q4VPdC4u/872-at042404-verify-notes-remark-input-field-has-a-booking-notes-text-placeholder

AT_04.24.04 | Verify Notes/Remark input field has a “Booking notes” text placeholder and is visible

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.07_ArrivalDropdown.cy.js
cypress/pageObjects/CreateBookingPage.js

TC - https://trello.com/c/qiwZUZ9f/903-tc040703-arrival-dropdown-ui-and-functionality-verify-that-the-background-of-the-selected-item-in-the-dropdown-menu-has-gray-col
AT - https://trello.com/c/g7lnWc2T/904-at040703-arrival-dropdown-ui-and-functionality-verify-that-the-background-of-the-selected-item-in-the-dropdown-menu-has-gray-col

AT_04.07.03 | Verify that the background of the selected item in the Dropdown Menu has gray color (#DDDDDD).

---

cypress/e2e/testUiAndFunction/startPage/US_01.10_LoginByPhoneNegative.cy.js
cypress/fixtures/startPage.json

https://trello.com/c/gsevCbep/912-at011005-start-page-login-by-phone-negative-verify-that-registering-is-not-possible-with-any-symbols-country-code-input

AT_01.10.05 | Verify that registering is not possible with any symbols "Country code" input'

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.07_ArrivalDropdown.cy.js

TC - https://trello.com/c/RZiaebQ2/940-tc040704-arrival-dropdown-ui-and-functionality-verify-that-the-background-of-the-newly-selected-item-changes-color-to-green00a65
AT - https://trello.com/c/1vo64A1z/941-at040704-arrival-dropdown-ui-and-functionality-verify-that-the-background-of-the-newly-selected-item-changes-color-to-green00a65

AT_04.07.04 | Verify that the background of the newly selected item changes color to green(#00A65A) when the item is selected.

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.19_UnselectedTripCardAvailable.cy.js

https://trello.com/c/L5PjPyHL/947-at041901-create-booking-page-unselected-trip-card-available-ui-verify-trips-card-with-number-available-tickets-label-is-visible

AT_04.19.01 | Verify Trips card with "Number available tickets" label is visible as unselected

---

cypress/e2e/testUiAndFunction/startPage/US_01.20_RestorePasswordPopupNegative.cy.js
cypress/fixtures/startPage.json

https://trello.com/c/US378qhU/972-tc012002-start-page-restore-password-popup-verify-that-the-user-is-not-able-to-restore-the-password-with-a-missing-domain-at-the

AT_01.20.02 | Verify that the user is not able to restore the password with a missing domain at the Email input

---

cypress/e2e/testUiAndFunction/createBookingPage/US_04.22_TripCardFunc.cy.js

https://trello.com/c/bqgfxN9Y/1062-at042207-create-booking-page-departure-on-trip-card-functionality-verify-when-trip-card-is-selected-summary-shows-default-select

AT_04.22.07 | Verify when trip card is selected, “Summary” shows default selected seat number
